# Generated by Django 2.1.1 on 2018-10-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=150)),
                ('components', models.TextField()),
                ('size_min', models.CharField(max_length=20)),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=4)),
                ('size_max', models.CharField(max_length=20)),
                ('price_max', models.DecimalField(decimal_places=2, max_digits=4)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
