# Generated by Django 2.1.1 on 2018-10-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_auto_20181019_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_extended',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_extended',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
