# Generated by Django 2.1.1 on 2018-10-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_auto_20181019_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=150)),
                ('components', models.TextField()),
                ('size_extended', models.CharField(max_length=20)),
                ('price_extended', models.DecimalField(decimal_places=2, max_digits=4)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_extended',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_extended',
        ),
    ]
