# Generated by Django 2.1.1 on 2018-10-22 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_auto_20181022_1403'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product1',
        ),
    ]
