# Generated by Django 2.1.1 on 2018-10-28 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0009_product_variation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Variation',
            new_name='Variation',
        ),
    ]
