# Generated by Django 2.1.1 on 2018-10-29 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0012_auto_20181029_2030'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'slug')},
        ),
    ]
