# Generated by Django 2.1.1 on 2018-10-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_remove_cartitem_variations'),
        ('menus', '0013_auto_20181029_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='product',
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
