# Generated by Django 2.1.1 on 2018-10-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_auto_20181019_1851'),
        ('cart', '0003_remove_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='menus.Product'),
        ),
    ]
