# Generated by Django 2.1.1 on 2018-10-28 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0010_auto_20181028_1946'),
        ('cart', '0008_auto_20181024_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menus.Variation'),
        ),
    ]
