# Generated by Django 2.1.1 on 2018-10-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0010_auto_20181028_1946'),
        ('cart', '0009_cartitem_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variation',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, null=True, to='menus.Variation'),
        ),
    ]
