# Generated by Django 2.1.1 on 2018-10-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_remove_cartitem_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
