# Generated by Django 2.1.1 on 2018-11-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_price_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
