# Generated by Django 2.1.1 on 2018-11-09 16:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0013_auto_20181030_1405'),
        ('orders', '0003_auto_20181109_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='ABC', max_length=120, unique=True)),
                ('price_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('person_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('payment', models.CharField(choices=[('-', '-'), ('Наличными', 'Наличными'), ('Карточкой', 'Карточкой')], default='-', max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart')),
            ],
        ),
    ]
