# Generated by Django 2.1.1 on 2018-11-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Started', 'Started'), ('Finished', 'Finished')], default='Started', max_length=120),
        ),
    ]
