# Generated by Django 2.1.1 on 2018-11-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=120, verbose_name='Ваше имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Контактный телефон')),
                ('payment', models.CharField(choices=[('-', '-'), ('Наличными', 'Наличными'), ('Карточкой', 'Карточкой')], default='-', max_length=120, verbose_name='Оплата')),
                ('address', models.CharField(max_length=120, verbose_name='Адрес')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
            ],
        ),
    ]
