# Generated by Django 2.1.1 on 2018-11-13 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_orderinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderInfo',
        ),
    ]
