# Generated by Django 2.1.1 on 2018-11-13 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20181113_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_info',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
    ]
