# Generated by Django 2.1.1 on 2018-11-13 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20181113_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderInfo',
        ),
    ]
