# Generated by Django 2.1.1 on 2018-11-13 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
