# Generated by Django 2.1.1 on 2018-11-13 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_auto_20181113_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.OrderInfo'),
        ),
    ]
