# Generated by Django 2.1.1 on 2018-11-13 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20181113_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_info',
        ),
    ]
