# Generated by Django 2.1.1 on 2018-12-01 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_cart_cartitem'),
        ('orders', '0031_remove_order_order_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Cart', verbose_name='Корзина'),
        ),
    ]
