# Generated by Django 2.1.1 on 2019-01-18 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_auto_20181201_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price_total',
        ),
    ]
