# Generated by Django 2.1.1 on 2018-09-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('working_hours', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('conditioner', models.BooleanField()),
            ],
        ),
    ]
