# Generated by Django 2.1.1 on 2018-09-24 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=50, verbose_name='Ваше имя')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Cafe', verbose_name='Район')),
            ],
        ),
    ]
