# Generated by Django 2.1.1 on 2018-09-24 12:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_booking_cafe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=50, verbose_name='Ваше имя')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время визита')),
                ('person_quantity', models.IntegerField(verbose_name='Количество людей')),
                ('phone', models.CharField(max_length=20, verbose_name='Контактный телефон')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Cafe', verbose_name='Район')),
            ],
        ),
        migrations.RemoveField(
            model_name='booking_cafe',
            name='district',
        ),
        migrations.DeleteModel(
            name='Booking_cafe',
        ),
    ]
