# Generated by Django 2.1.1 on 2018-09-24 12:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_auto_20180924_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 9, 24, 12, 33, 13, 96933, tzinfo=utc)),
        ),
    ]
