# Generated by Django 2.1.1 on 2018-09-24 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_auto_20180924_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='send',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время отправки'),
        ),
    ]
