# Generated by Django 2.1.1 on 2018-09-24 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_auto_20180924_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='send',
            new_name='created_at',
        ),
    ]
