# Generated by Django 2.1.1 on 2018-09-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0009_auto_20180925_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(max_length=20, verbose_name='Время визита'),
        ),
    ]
