# Generated by Django 2.1.1 on 2018-10-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0010_auto_20180925_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
