# Generated by Django 2.1.1 on 2018-10-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0012_auto_20181003_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
